/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package AnalizadorD;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int NUMERIC = 8;
  /** RegularExpression Id. */
  int PYCOMA = 9;
  /** RegularExpression Id. */
  int MAS = 10;
  /** RegularExpression Id. */
  int MENOS = 11;
  /** RegularExpression Id. */
  int POR = 12;
  /** RegularExpression Id. */
  int DIV = 13;
  /** RegularExpression Id. */
  int COMA = 14;
  /** RegularExpression Id. */
  int POTENCIA = 15;
  /** RegularExpression Id. */
  int MODULO = 16;
  /** RegularExpression Id. */
  int PAR_A = 17;
  /** RegularExpression Id. */
  int PAR_C = 18;
  /** RegularExpression Id. */
  int COR_A = 19;
  /** RegularExpression Id. */
  int COR_C = 20;
  /** RegularExpression Id. */
  int LLAV_A = 21;
  /** RegularExpression Id. */
  int LLAV_C = 22;
  /** RegularExpression Id. */
  int IGUAL = 23;
  /** RegularExpression Id. */
  int DISTINTO = 24;
  /** RegularExpression Id. */
  int IGUAL_IGUAL = 25;
  /** RegularExpression Id. */
  int MAYOR_I = 26;
  /** RegularExpression Id. */
  int MENOR_I = 27;
  /** RegularExpression Id. */
  int MAYOR = 28;
  /** RegularExpression Id. */
  int IGUAL_MAYOR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int AND = 31;
  /** RegularExpression Id. */
  int OR = 32;
  /** RegularExpression Id. */
  int NOT = 33;
  /** RegularExpression Id. */
  int BOOLEANO = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int SWITCH = 37;
  /** RegularExpression Id. */
  int DO = 38;
  /** RegularExpression Id. */
  int WHILE = 39;
  /** RegularExpression Id. */
  int CASE = 40;
  /** RegularExpression Id. */
  int PREGUNTA = 41;
  /** RegularExpression Id. */
  int NULO = 42;
  /** RegularExpression Id. */
  int TDEFAULT = 43;
  /** RegularExpression Id. */
  int BREAK = 44;
  /** RegularExpression Id. */
  int CONTINUE = 45;
  /** RegularExpression Id. */
  int FUNCTION = 46;
  /** RegularExpression Id. */
  int FOR = 47;
  /** RegularExpression Id. */
  int IN = 48;
  /** RegularExpression Id. */
  int DOSPUNTOS = 49;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 50;
  /** RegularExpression Id. */
  int NOVAL = 51;
  /** RegularExpression Id. */
  int STRING = 54;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER>",
    "<NUMERIC>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\"^\"",
    "\"%%\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"=>\"",
    "\"<\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<BOOLEANO>",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"do\"",
    "\"while\"",
    "\"case\"",
    "\"?\"",
    "\"null\"",
    "\"default\"",
    "\"break\"",
    "\"continue\"",
    "\"function\"",
    "\"for\"",
    "\"in\"",
    "\":\"",
    "<IDENTIFICADOR>",
    "<NOVAL>",
    "\"\\\"\"",
    "<token of kind 53>",
    "\"\\\"\"",
  };

}
