/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package AnalizadorD;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int NUMERIC = 8;
  /** RegularExpression Id. */
  int PYCOMA = 9;
  /** RegularExpression Id. */
  int MAS = 10;
  /** RegularExpression Id. */
  int MENOS = 11;
  /** RegularExpression Id. */
  int POR = 12;
  /** RegularExpression Id. */
  int DIV = 13;
  /** RegularExpression Id. */
  int POTENCIA = 14;
  /** RegularExpression Id. */
  int MODULO = 15;
  /** RegularExpression Id. */
  int PAR_A = 16;
  /** RegularExpression Id. */
  int PAR_C = 17;
  /** RegularExpression Id. */
  int COR_A = 18;
  /** RegularExpression Id. */
  int COR_C = 19;
  /** RegularExpression Id. */
  int LLAV_A = 20;
  /** RegularExpression Id. */
  int LLAV_C = 21;
  /** RegularExpression Id. */
  int IGUAL = 22;
  /** RegularExpression Id. */
  int DISTINTO = 23;
  /** RegularExpression Id. */
  int IGUAL_IGUAL = 24;
  /** RegularExpression Id. */
  int MAYOR_I = 25;
  /** RegularExpression Id. */
  int MENOR_I = 26;
  /** RegularExpression Id. */
  int MAYOR = 27;
  /** RegularExpression Id. */
  int MENOR = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int BOOLEANO = 32;
  /** RegularExpression Id. */
  int PREGUNTA = 33;
  /** RegularExpression Id. */
  int PRINT = 34;
  /** RegularExpression Id. */
  int NULO = 35;
  /** RegularExpression Id. */
  int DOSPUNTOS = 36;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 37;
  /** RegularExpression Id. */
  int STRING = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER>",
    "<NUMERIC>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"%%\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<BOOLEANO>",
    "\"?\"",
    "\"print\"",
    "\"null\"",
    "\":\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 39>",
    "\"\\\"\"",
  };

}
